<a href="https://colab.research.google.com/github/Faris2007kh/GDG/blob/main/NumPy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Assignment

Complete the exercises below to test your understanding of NumPy. Each question tells you what output or result is expected. Write your code in the provided code cells.

**Topics covered:**
- Creating arrays (from lists, built-in methods)
- Random number generation
- Array attributes and methods
- Indexing and slicing
- Broadcasting
- Boolean masking
- NumPy operations

In [1]:
# Run this cell first!
import numpy as np

---
## Part 1: Creating Arrays

### Q1. Convert the following Python list into a NumPy array and store it in a variable called `arr1`.
```python
my_list = [10, 20, 30, 40, 50]
```

In [3]:
# Your code here

my_list = [10, 20, 30, 40, 50]
arr1 = np.array(my_list)

print(arr1)

[10 20 30 40 50]


### Q2. Convert the following list of lists into a 2D NumPy array and store it in `mat1`.
```python
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
```

In [4]:
# Your code here

my_matrix = [[1, 2, 3],
             [4, 5, 6],
             [7, 8, 9]]

mat1 = np.array(my_matrix)

print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### Q3. Use `np.arange` to create an array of all even numbers from 0 to 20 (inclusive).

In [5]:
# Expected output: array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
# Your code here

even_numbers = np.arange(0, 21, 2)

print(even_numbers)

[ 0  2  4  6  8 10 12 14 16 18 20]


### Q4. Create a 4x4 array of all zeros.

In [6]:
# Your code here

zeros_array = np.zeros((4, 4))

print(zeros_array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Q5. Create a 3x5 array of all ones.

In [7]:
# Your code here

ones_array = np.ones((3, 5))

print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


### Q6. Use `np.linspace` to create an array of 10 evenly spaced values between 0 and 5.

In [8]:
# Your code here

evenly_spaced_array = np.linspace(0, 5, 10)

print(evenly_spaced_array)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Q7. Create a 5x5 identity matrix using NumPy.

In [9]:
# Your code here

identity_matrix = np.eye(5)

print(identity_matrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


---
## Part 2: Random Number Generation

### Q8. Create a 3x3 array of random floats drawn from a uniform distribution between 0 and 1.

In [10]:
# Your code here

random_array = np.random.rand(3, 3)

print(random_array)

[[0.89789653 0.31700829 0.6856742 ]
 [0.74297935 0.89894066 0.49061963]
 [0.24162763 0.24590102 0.7868073 ]]


### Q9. Create a 1D array of 5 random floats drawn from a standard normal distribution.

In [11]:
# Your code here

random_array = np.random.randn(5)

print(random_array)

[ 0.3538704  -0.37833457 -0.48974457  0.36081402  0.970225  ]


### Q10. Create an array of 8 random integers between 1 and 100 (inclusive of 1, exclusive of 100).

In [12]:
# Your code here

random_array = np.random.randint(1, 100, 8)

print(random_array)

[77 58 59 79 16 27 97 53]


---
## Part 3: Array Attributes & Methods

Run the cell below to create the arrays you'll use for this section.

In [13]:

np.random.seed(42)
arr = np.arange(36)
ranarr = np.random.randint(0, 100, 12)
print('arr:', arr)
print('ranarr:', ranarr)


arr: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
ranarr: [51 92 14 71 60 20 82 86 74 74 87 99]


### Q11. Reshape `arr` into a 6x6 matrix.

In [14]:
# Your code here

reshaped_arr = arr.reshape(6, 6)

print(reshaped_arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


### Q12. Find the maximum value in `ranarr`.

In [15]:
# Your code here

max_value = np.max(ranarr)

print(max_value)

99


### Q13. Find the index position of the minimum value in `ranarr`.

In [16]:
# Your code here

min_index = np.argmin(ranarr)

print(min_index)


2


### Q14. What is the shape of `arr`? What is its shape after reshaping to (1, 36)?

In [17]:
# Your code here

print("Shape of arr:", arr.shape)


Shape of arr: (36,)


### Q15. What is the data type (`dtype`) of the elements in `arr`?

In [18]:
# Your code here

print("Data type of elements in arr:", arr.dtype)

Data type of elements in arr: int64


---
## Part 4: Indexing and Slicing

Run the cell below to set up the array for this section.

In [19]:
arr = np.arange(0, 11)
mat = np.arange(1, 26).reshape(5, 5)
print('arr:', arr)
print('mat:\n', mat)

arr: [ 0  1  2  3  4  5  6  7  8  9 10]
mat:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


### Q16. From `arr`, retrieve the value at index 7.

In [20]:
# Expected output: 7
# Your code here

print(arr[7])

7


### Q17. From `arr`, retrieve values from index 3 to 7 (inclusive of 3, exclusive of 7).

In [21]:
# Expected output: array([3, 4, 5, 6])
# Your code here

print(arr[3:7])

[3 4 5 6]


### Q18. From `mat`, retrieve the bottom-right 3x3 submatrix.
Expected output:
```
array([[13, 14, 15],
       [18, 19, 20],
       [23, 24, 25]])
```

In [22]:
# Your code here

print(mat[2:, 2:])

[[13 14 15]
 [18 19 20]
 [23 24 25]]


### Q19. From `mat`, retrieve only the element `17`.

In [24]:
# Expected output: 17
# Your code here

print(mat[3, 1])

17


### Q20. From `mat`, retrieve the first column as a 2D column vector (shape should be (5,1)).
Expected output:
```
array([[ 1],
       [ 6],
       [11],
       [16],
       [21]])
```

In [28]:
# Your code here
print(mat[:, 0].reshape(-1, 1))

[[ 1]
 [ 6]
 [11]
 [16]
 [21]]


### Q21. From `mat`, retrieve the entire third row.
Expected output: `array([11, 12, 13, 14, 15])`

In [29]:
# Your code here
print(mat[2, :])

[11 12 13 14 15]


---
## Part 5: Broadcasting

### Q22. Using `arr = np.arange(0, 11)`, set all values from index 2 to 5 (inclusive) to the value `50`. Print the result.

In [30]:
arr = np.arange(0, 11)
# Your code here

arr[2:6] = 50
print(arr)

[ 0  1 50 50 50 50  6  7  8  9 10]


### Q23. Create a copy of `arr` (from its original state below) and set all values to 0 in the copy. Verify that the original `arr` is unchanged.

In [31]:
arr = np.arange(0, 11)
# Your code here — create a copy, modify the copy, then print both

arr_copy = arr.copy()
arr_copy[:] = 0

print("Original arr:", arr)
print("Copied arr:", arr_copy)

Original arr: [ 0  1  2  3  4  5  6  7  8  9 10]
Copied arr: [0 0 0 0 0 0 0 0 0 0 0]


---
## Part 6: Boolean Masking & Conditional Selection

Run the cell below first.

In [32]:
arr = np.arange(1, 21)  # 1 through 20
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

### Q24. Create a boolean mask for all values in `arr` that are greater than 10, and use it to retrieve those values.

In [33]:
# Expected output: array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# Your code here

mask = arr > 10
filtered_arr = arr[mask]

print(filtered_arr)

[11 12 13 14 15 16 17 18 19 20]


### Q25. Retrieve all even numbers from `arr` using boolean indexing.
*Hint: use the modulo operator `%`*

In [34]:
# Expected output: array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])
# Your code here

even_numbers = arr[arr % 2 == 0]

print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20]


---
## Part 7: NumPy Operations & Statistics

Run this cell to set up `mat`.

In [35]:
mat = np.arange(1, 26).reshape(5, 5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Q26. Get the sum of all values in `mat`.

In [36]:
# Expected output: 325
# Your code here

total_sum = np.sum(mat)

print(total_sum)

325


### Q27. Get the standard deviation of all values in `mat`.

In [37]:
# Your code here

std_deviation = np.std(mat)

print(std_deviation)

7.211102550927978


### Q28. Get the sum of each **column** in `mat`.
Expected output: `array([55, 60, 65, 70, 75])`

In [38]:
# Your code here

column_sums = np.sum(mat, axis=0)

print(column_sums)

[55 60 65 70 75]


### Q29. Get the sum of each **row** in `mat`.
Expected output: `array([ 15,  40,  65,  90, 115])`

In [39]:
# Your code here

row_sums = np.sum(mat, axis=1)

print(row_sums)

[ 15  40  65  90 115]


### Q30. Find the mean of all values in `mat`.

In [40]:
# Your code here

mean_value = np.mean(mat)

print(mean_value)

13.0


---
## Bonus Challenge

### B1. Create a 4x4 array of random integers between 1 and 50. Then:
1. Print the array
2. Print its transpose
3. Print the element-wise square root of the array (use `np.sqrt`)
4. Print the index of the largest value in the flattened array

In [41]:
np.random.seed(0)  # Keep this for reproducibility
# Your code here

random_array = np.random.randint(1, 51, size=(4, 4))

print("Original Array:")
print(random_array)

print("\nTranspose of the Array:")
print(random_array.T)

print("\nElement-wise Square Root:")
print(np.sqrt(random_array))

flattened_array = random_array.flatten()
max_index = np.argmax(flattened_array)

print("\nIndex of the Largest Value (Flattened):", max_index)

Original Array:
[[45 48  1  4]
 [ 4 40 10 20]
 [22 37 24  7]
 [25 25 13  2]]

Transpose of the Array:
[[45  4 22 25]
 [48 40 37 25]
 [ 1 10 24 13]
 [ 4 20  7  2]]

Element-wise Square Root:
[[6.70820393 6.92820323 1.         2.        ]
 [2.         6.32455532 3.16227766 4.47213595]
 [4.69041576 6.08276253 4.89897949 2.64575131]
 [5.         5.         3.60555128 1.41421356]]

Index of the Largest Value (Flattened): 1


### B2. Using only NumPy, create an 8x8 checkerboard pattern (0s and 1s).
Expected output:
```
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 ...]
```
*Hint: Try using `np.zeros` and index slicing with steps.*

In [43]:
# Your code here

checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


---
# Great Job! 🎉
Once you're done, review your answers and make sure each cell produces the expected output.